// <auto-generated />
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;
using RangoAgilApi.DbContexts;

#nullable disable

namespace RangoAgilApi.Migrations
{
    [DbContext(typeof(RangoDbContext))]
    [Migration("20240701140327_Initial")]
    partial class Initial
    {
        /// <inheritdoc />
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder.HasAnnotation("ProductVersion", "8.0.6");

            modelBuilder.Entity("IngredienteRango", b =>
                {
                    b.Property<int>("IngredientesId")
                        .HasColumnType("INTEGER");

                    b.Property<int>("RangosId")
                        .HasColumnType("INTEGER");

                    b.HasKey("IngredientesId", "RangosId");

                    b.HasIndex("RangosId");

                    b.ToTable("IngredienteRango");

                    b.HasData(
                        new
                        {
                            IngredientesId = 1,
                            RangosId = 1
                        },
                        new
                        {
                            IngredientesId = 2,
                            RangosId = 1
                        },
                        new
                        {
                            IngredientesId = 1,
                            RangosId = 2
                        },
                        new
                        {
                            IngredientesId = 3,
                            RangosId = 2
                        },
                        new
                        {
                            IngredientesId = 1,
                            RangosId = 3
                        },
                        new
                        {
                            IngredientesId = 5,
                            RangosId = 3
                        },
                        new
                        {
                            IngredientesId = 2,
                            RangosId = 3
                        },
                        new
                        {
                            IngredientesId = 1,
                            RangosId = 4
                        },
                        new
                        {
                            IngredientesId = 3,
                            RangosId = 4
                        },
                        new
                        {
                            IngredientesId = 5,
                            RangosId = 5
                        });
                });

            modelBuilder.Entity("RangoAgilApi.Entities.Ingrediente", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Ingredientes");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Pão"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Carne de Vaca"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Cebola"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Maionese"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Alface"
                        });
                });

            modelBuilder.Entity("RangoAgilApi.Entities.Rango", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("INTEGER");

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasMaxLength(200)
                        .HasColumnType("TEXT");

                    b.HasKey("Id");

                    b.ToTable("Rangos");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Subway"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Pizza"
                        },
                        new
                        {
                            Id = 3,
                            Name = "Sopa"
                        },
                        new
                        {
                            Id = 4,
                            Name = "Espaguete"
                        },
                        new
                        {
                            Id = 5,
                            Name = "Lasanha"
                        });
                });

            modelBuilder.Entity("IngredienteRango", b =>
                {
                    b.HasOne("RangoAgilApi.Entities.Ingrediente", null)
                        .WithMany()
                        .HasForeignKey("IngredientesId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("RangoAgilApi.Entities.Rango", null)
                        .WithMany()
                        .HasForeignKey("RangosId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
